// AUTO-GENERATED by scanner.js — do not edit manually
var COMPONENT_MAP = {
  ".govuk-button": {
    "name": "Button type=Default, State=Focus",
    "key": "d01a450cd6b2d2378317cc824641e64193a95847",
    "description": "Button type=Default, State=Focus",
    "docsUrl": "https://design-system.service.gov.uk/components/button/"
  },
  ".govuk-file-upload": {
    "name": "File upload state=Hover, Uploaded content=False",
    "key": "d7d49eef9883a9c7e8ef25d6164215bea362c418",
    "description": "File upload state=Hover, Uploaded content=False",
    "docsUrl": "https://design-system.service.gov.uk/components/file-upload/"
  },
  ".govuk-breadcrumbs": {
    "name": "Breadcrumbs",
    "key": "7e37f00f74e361e7dacd2315587de8c1fb33f8e9",
    "description": "Breadcrumbs",
    "docsUrl": null
  },
  ".govuk-table": {
    "name": "Table row",
    "key": "9512a9dbad7b3a43d0dd06e14b27d8990113e5ea",
    "description": "Table row",
    "docsUrl": "https://design-system.service.gov.uk/components/table/"
  },
  ".govuk-exit-this-page": {
    "name": "Exit this page",
    "key": "500b9cc29de01aa1f8de9efc8e75099afbd76da7",
    "description": "Exit this page",
    "docsUrl": null
  },
  ".govuk-tabs__list-item--selected": {
    "name": "Tab state=Selected, State=Default",
    "key": "2b55b4f70ac1f7705e21091739082eee52734294",
    "description": "Tab state=Selected, State=Default",
    "docsUrl": null
  },
  ".govuk-task-list": {
    "name": "Task list status=Default",
    "key": "2321c3af1975dd4112035b7e794d0d606e3e7288",
    "description": "Task list status=Default",
    "docsUrl": "https://design-system.service.gov.uk/components/task-list/"
  },
  ".govuk-body-s": {
    "name": "Size=Small, Weight=Bold",
    "key": "f3d61ba7d7a085909ee65a002dd635fc124deb8a",
    "description": "Size=Small, Weight=Bold",
    "docsUrl": null
  },
  ".govuk-select": {
    "name": "Select state=Default",
    "key": "e4ccf531b45965d5b9330d3402c4068174f246dd",
    "description": "Select state=Default",
    "docsUrl": "https://design-system.service.gov.uk/components/select/"
  },
  ".govuk-checkboxes": {
    "name": "Checkbox size=Small",
    "key": "a8036d221d249a1f4bbe53e89e0443d4859ac2fe",
    "description": "Checkbox size=Small",
    "docsUrl": "https://design-system.service.gov.uk/components/checkboxes/"
  },
  ".govuk-password-input": {
    "name": "Password input=Default",
    "key": "f3bda835e5aa8625a4e1096ae3d6fd2f36ef2e65",
    "description": "Password input=Default",
    "docsUrl": "https://design-system.service.gov.uk/components/password-input/"
  },
  ".govuk-accordion": {
    "name": "Accordion",
    "key": "ad7f28fc0fd6d8e37e4494b76b462be6e4e6c890",
    "description": "Accordion",
    "docsUrl": null
  },
  ".govuk-service-navigation": {
    "name": "Service navigation",
    "key": "2ba40023a11720efc3b6e545c1990653aa58d00a",
    "description": "Service navigation",
    "docsUrl": "https://design-system.service.gov.uk/components/service-navigation/"
  },
  ".govuk-section-break--xl": {
    "name": "Section break size=XL",
    "key": "a4f43d82fcea30cc4f93692306bdbe1c260527a0",
    "description": "Section break size=XL",
    "docsUrl": null
  },
  ".govuk-header": {
    "name": "GOV.UK header",
    "key": "47843be9ef982ca391bb304355d0b677fbe6dda8",
    "description": "GOV.UK header",
    "docsUrl": null
  },
  ".govuk-tag--blue": {
    "name": "Tag class=govuk-tag--blue",
    "key": "1352b9d92096bc932f64635260af41843e8cebea",
    "description": "Tag class=govuk-tag--blue",
    "docsUrl": null
  },
  ".govuk-tag--orange": {
    "name": "Tag class=govuk-tag--orange",
    "key": "57385d89503dacfe96c71d862f2d16695a99d712",
    "description": "Tag class=govuk-tag--orange",
    "docsUrl": null
  },
  ".govuk-heading-l": {
    "name": "Size=L",
    "key": "0b03db432cafb474f4d1e6a4c0c24aac9923b4c3",
    "description": "Size=L",
    "docsUrl": null
  },
  ".govuk-body-l": {
    "name": "Size=Large, Weight=Bold",
    "key": "2571155a5fc3878d9eb69444463eb390fe520ba1",
    "description": "Size=Large, Weight=Bold",
    "docsUrl": null
  },
  ".govuk-tag--magenta": {
    "name": "Tag class=govuk-tag--magenta",
    "key": "cf2c66dfdbac761dfbb6740910bef8f5ef8e002b",
    "description": "Tag class=govuk-tag--magenta",
    "docsUrl": null
  },
  ".govuk-tag--red": {
    "name": "Tag class=govuk-tag--red",
    "key": "30421f6acfeeab0b1aec8164c22ba82611810489",
    "description": "Tag class=govuk-tag--red",
    "docsUrl": null
  },
  ".govuk-inset-text": {
    "name": "Inset text",
    "key": "0bc8cedb562940c33b19f631e6792a7d2a5e1817",
    "description": "Inset text",
    "docsUrl": null
  },
  ".govuk-tag--purple": {
    "name": "Tag class=govuk-tag--purple",
    "key": "56447a73d95d3a1e05b75a6854e0974e87c55eef",
    "description": "Tag class=govuk-tag--purple",
    "docsUrl": null
  },
  ".govuk-warning-text": {
    "name": "Warning text",
    "key": "3a52f820a3b7577b2ac48211758d0f200fe8cd9c",
    "description": "Warning text",
    "docsUrl": null
  },
  ".govuk-details": {
    "name": "Details=Revealed",
    "key": "68aefb45bb46b4ea4c6f526e0b727be7b89d4594",
    "description": "Details=Revealed",
    "docsUrl": "https://design-system.service.gov.uk/components/details/"
  },
  ".govuk-list": {
    "name": "List item",
    "key": "6de30c1bc1c24f10d8bc7baad8c73b19ddd33797",
    "description": "List item",
    "docsUrl": null
  },
  ".govuk-button--inverse": {
    "name": "Button type=Inverse, State=Default",
    "key": "4292fc317fb67ae30852964fa1090ea3e37e74d6",
    "description": "Button type=Inverse, State=Default",
    "docsUrl": null
  },
  ".govuk-cookie-banner": {
    "name": "Cookie banner size=Desktop",
    "key": "9026293f6f31ae07ba6e70578d573dedc54bb812",
    "description": "Cookie banner size=Desktop",
    "docsUrl": "https://design-system.service.gov.uk/components/cookie-banner/"
  },
  ".govuk-error-summary": {
    "name": "Error summary",
    "key": "05c51bde602e3e3403b6395efb72b0838386ed40",
    "description": "Error summary",
    "docsUrl": null
  },
  ".govuk-pagination--block": {
    "name": "Pagination",
    "key": "59badfb1b67114b7819e3d6952c09f51c6f44a47",
    "description": "Pagination",
    "docsUrl": null
  },
  ".govuk-pagination": {
    "name": "Pagination",
    "key": "5af2b028b8ca23b6db582d0e04b6b74a5106bcb7",
    "description": "Pagination",
    "docsUrl": null
  },
  ".govuk-phase-banner": {
    "name": "Phase banner",
    "key": "8c4dc9e6810c6d431e13e6976f2c8f0117d5eb71",
    "description": "Phase banner",
    "docsUrl": null
  },
  ".govuk-tag--green": {
    "name": "Tag class=govuk-tag--green",
    "key": "2fcd4084ba61bee70d7ebd306f078fbce8317444",
    "description": "Tag class=govuk-tag--green",
    "docsUrl": null
  },
  ".govuk-heading-xl": {
    "name": "Size=XL",
    "key": "333a1f28b8df201f9de795fdc571811fe1af52fb",
    "description": "Size=XL",
    "docsUrl": null
  },
  ".govuk-service-navigation__item--active": {
    "name": "State=Selected, Viewport=Mobile",
    "key": "4d586e3918faa6cb4626b7fb74c5d68b56d0436f",
    "description": "State=Selected, Viewport=Mobile",
    "docsUrl": null
  },
  ".govuk-tag--yellow": {
    "name": "Tag class=govuk-tag--yellow",
    "key": "4d6bb537ecb203519053f2ab022d2d638121c5aa",
    "description": "Tag class=govuk-tag--yellow",
    "docsUrl": null
  },
  ".govuk-body": {
    "name": "Size=Default, Weight=Light",
    "key": "525915a0c820c40078f3fc6bb2e10553f9515be3",
    "description": "Size=Default, Weight=Light",
    "docsUrl": null
  },
  ".govuk-notification-banner--success": {
    "name": "Banner type=Success",
    "key": "581f8496d154fc22b916614a2b76018e14b521b1",
    "description": "Banner type=Success",
    "docsUrl": null
  },
  ".govuk-tag--grey": {
    "name": "Tag class=govuk-tag--grey",
    "key": "91a3199c47a52bedc2fd876c19c99725aa215175",
    "description": "Tag class=govuk-tag--grey",
    "docsUrl": null
  },
  ".govuk-heading-s": {
    "name": "Size=S",
    "key": "b26b1b4c33b4fb0e1e3d3c484764ddc3fa30094c",
    "description": "Size=S",
    "docsUrl": null
  },
  ".govuk-tag--teal": {
    "name": "Tag class=govuk-tag--teal",
    "key": "ebb56159d0f3ec859ffcbeac0d077003e3b57f6b",
    "description": "Tag class=govuk-tag--teal",
    "docsUrl": null
  },
  ".govuk-heading-m": {
    "name": "Size=M",
    "key": "ed86f741e875feb7f8d5b8eeb4cb3d0205457de1",
    "description": "Size=M",
    "docsUrl": null
  },
  ".govuk-skip-link": {
    "name": "Skip link",
    "key": "15994885c7bb0cf8e1a689b2f118403de58efa13",
    "description": "Skip link",
    "docsUrl": null
  },
  ".govuk-task-list__status": {
    "name": "Task list",
    "key": "43f75c7ca2adabe43517642c77c0d8eba2ce0a33",
    "description": "Task list",
    "docsUrl": null
  },
  ".govuk-button--warning": {
    "name": "Button type=Warning, State=Default",
    "key": "4c4fdc06a935e0dbdd74ad0e2426b8e4c19b9a1a",
    "description": "Button type=Warning, State=Default",
    "docsUrl": null
  },
  ".govuk-tabs": {
    "name": "Tabs",
    "key": "8495b4b4efed00cb47e48b737fd614260c21a338",
    "description": "Tabs",
    "docsUrl": null
  },
  ".govuk-button--start": {
    "name": "Button type=Start button, State=Default",
    "key": "ad9c2b73f965ec53b82e55db075e28131deb4d6b",
    "description": "Button type=Start button, State=Default",
    "docsUrl": null
  },
  ".govuk-panel": {
    "name": "Panel",
    "key": "b5f7dd8a24e6be3a18da3e421f0d217b93ae3593",
    "description": "Panel",
    "docsUrl": null
  },
  ".govuk-tabs__panel": {
    "name": "Tab body",
    "key": "bac2050d73c075221930ef62e4495fedcdd66366",
    "description": "Tab body",
    "docsUrl": null
  },
  ".govuk-button--secondary": {
    "name": "Button type=Secondary, State=Default",
    "key": "ef1085d61e023018bf29ee8b096b4de4bd6cc767",
    "description": "Button type=Secondary, State=Default",
    "docsUrl": null
  },
  ".govuk-footer": {
    "name": "GOV.UK footer",
    "key": "61d1e7445aa73c901fc7e6eca51bfac88693bd10",
    "description": "GOV.UK footer",
    "docsUrl": null
  },
  ".govuk-section-break--l": {
    "name": "Section break size=Large",
    "key": "b423275788d3a69e8ea5d20776b0ae22dfac5b8c",
    "description": "Section break size=Large",
    "docsUrl": null
  },
  ".govuk-section-break--m": {
    "name": "Section break size=Medium",
    "key": "e9425a9f0f37f26a2c3f6df42f768a90edd50d59",
    "description": "Section break size=Medium",
    "docsUrl": null
  },
  ".gem-c-layout-super-navigation-header": {
    "name": "Header",
    "key": "e588a561881d6fac3a8c39c7a142a9fcfefc82d4",
    "description": "Header",
    "docsUrl": null
  },
  ".gem-c-select": {
    "name": "Select with search dropdown",
    "key": "392d1e01e6a8fd0508b5c5369c304d19c1dddf2e",
    "description": "Select with search dropdown",
    "docsUrl": "https://components.publishing.service.gov.uk/component-guide/select"
  },
  ".gem-c-heading": {
    "name": "Heading presentation=Default",
    "key": "57f4592b68af6a4b6e5f70b2ecd260ce33a198c5",
    "description": "Heading presentation=Default",
    "docsUrl": "https://components.publishing.service.gov.uk/component-guide/heading"
  },
  ".gem-c-subscription-links": {
    "name": "Subscription links",
    "key": "280ecae13b5bdffe05d6542420383f483fe805b3",
    "description": "Subscription links",
    "docsUrl": "https://components.publishing.service.gov.uk/component-guide/subscription_links"
  },
  ".gem-c-contextual-sidebar": {
    "name": "Contextual sidebar",
    "key": "02e71c5c8894e76217c6a99d39a23d79ef8e5a7c",
    "description": "Contextual sidebar",
    "docsUrl": null
  },
  ".gem-c-back-to-top-link": {
    "name": "Back to the top link",
    "key": "2eb5b3a9bb988a17ed880a9474b91035bc46b804",
    "description": "Back to the top link",
    "docsUrl": null
  },
  ".gem-c-devolved-nations": {
    "name": "Devolved nations",
    "key": "7aa5af6cfb846637e5e1c90cf9bf1c8abed594bd",
    "description": "Devolved nations",
    "docsUrl": null
  },
  ".gem-c-published-dates": {
    "name": "Published dates",
    "key": "ad66cf28f86d43ca0c11a52a309325b2a0efa19a",
    "description": "Published dates",
    "docsUrl": "https://components.publishing.service.gov.uk/component-guide/published_dates"
  },
  ".gem-c-translation-nav": {
    "name": "Translation nav",
    "key": "5c304925196cfd2b240d76f76bfd71a068e1dbb0",
    "description": "Translation nav",
    "docsUrl": null
  },
  ".gem-c-copy-to-clipboard": {
    "name": "Copy to clipboard",
    "key": "322d0a1daa8c178a6367f76595ca48a21f3711d5",
    "description": "Copy to clipboard",
    "docsUrl": null
  },
  ".gem-c-reorderable-list__item": {
    "name": "Reordable list item",
    "key": "62e1ece52e846a5047678427b305602ef4c41dbb",
    "description": "Reordable list item",
    "docsUrl": null
  },
  ".gem-c-cross-service-header": {
    "name": "Header",
    "key": "02c3a39aa8836192939e5d42110b1222fe172ae5",
    "description": "Header",
    "docsUrl": null
  },
  ".gem-c-list": {
    "name": "List orientation=Vertical",
    "key": "2926c7ce48dd0ec2913281a8819520ac21170a6f",
    "description": "List orientation=Vertical",
    "docsUrl": "https://components.publishing.service.gov.uk/component-guide/list"
  },
  ".gem-c-action-link--large": {
    "name": "Size=Large",
    "key": "3b0e17b25261340fb779f3130638168187090b0a",
    "description": "Size=Large",
    "docsUrl": null
  },
  ".gem-c-attachment__thumbnail-image--external": {
    "name": "Attachment icon=external",
    "key": "4bc489c08a7ac20a5e9025b23da81d08d7c55eee",
    "description": "Attachment icon=external",
    "docsUrl": null
  },
  ".gem-c-attachment__thumbnail-image--spreadsheet": {
    "name": "Attachment icon=text",
    "key": "4bd9b75f418544963783d309ac67807b1c127929",
    "description": "Attachment icon=text",
    "docsUrl": null
  },
  ".gem-c-attachment": {
    "name": "Attachment",
    "key": "5bd218eb66b017c9d41b51d1806baf25fc039c44",
    "description": "Attachment",
    "docsUrl": null
  },
  ".gem-c-summary-banner": {
    "name": "Summary banner",
    "key": "5bc046701800ffb41be9a3c280224ba43f857741",
    "description": "Summary banner",
    "docsUrl": null
  },
  ".gem-c-layout-header": {
    "name": "Header",
    "key": "7fac6fe69619e5c09afc3bf89f7746d8960e9424",
    "description": "Header",
    "docsUrl": null
  },
  ".gem-c-attachment__thumbnail-image--html": {
    "name": "Attachment icon=html",
    "key": "7968c91d56993e8370168a5e8c68510ff2a67258",
    "description": "Attachment icon=html",
    "docsUrl": null
  },
  ".gem-c-attachment__thumbnail-image--pdf": {
    "name": "Attachment icon=application",
    "key": "8019c8f94cfe02f9bb8d66d528a32a8c651c7543",
    "description": "Attachment icon=application",
    "docsUrl": null
  },
  ".gem-c-secondary-navigation__list-item--current": {
    "name": "State=Selected, Viewport=Mobile",
    "key": "b87f6ed417e0aad04e2992101b9fc7bfae1d52db",
    "description": "State=Selected, Viewport=Mobile",
    "docsUrl": null
  },
  ".gem-c-secondary-navigation__list-item-link": {
    "name": "State=Default, Viewport=Mobile",
    "key": "ca77a898b6097a99c4b3cc080273dabaccbe247a",
    "description": "State=Default, Viewport=Mobile",
    "docsUrl": null
  },
  ".gem-c-emergency-banner--local-emergency": {
    "name": "Campaign class=Local emergency",
    "key": "048a53e846f21c5ef785711c9558cdc863456611",
    "description": "Campaign class=Local emergency",
    "docsUrl": null
  },
  ".gem-c-glance-metric": {
    "name": "Glance metric",
    "key": "1fde2e0799bc1b5d68e8276efc7fe4cb34c25771",
    "description": "Glance metric",
    "docsUrl": null
  },
  ".gem-c-emergency-banner--national-emergency": {
    "name": "Campaign class=National emergency",
    "key": "5b3b08a607511e5e27205968063635eba4b16ce0",
    "description": "Campaign class=National emergency",
    "docsUrl": null
  },
  ".gem-c-document-list": {
    "name": "Document list",
    "key": "815e97a96e1ddc6b2f3d0eda6f1c0ae8310ee957",
    "description": "Document list",
    "docsUrl": null
  },
  ".gem-c-cards": {
    "name": "Cards",
    "key": "a633178874c75f37ebc2503c108f29ff99c97479",
    "description": "Cards",
    "docsUrl": null
  },
  ".gem-c-document-list__item": {
    "name": "Document List item",
    "key": "a8f35b85ae565c806dd9c257508fb7a673580a3b",
    "description": "Document List item",
    "docsUrl": null
  },
  ".gem-c-big-number": {
    "name": "Big Number",
    "key": "bf3f7e41b6c3eefaf6bc9cfd690ab015442bd715",
    "description": "Big Number",
    "docsUrl": null
  },
  ".gem-c-contextual-footer": {
    "name": "Contextual footer",
    "key": "ce2e79b4a5c4abe9218434e342493d32ffa4a474",
    "description": "Contextual footer",
    "docsUrl": null
  },
  ".gem-c-search": {
    "name": "Search",
    "key": "d2d7a85899d53b4de4b2fd7f2c8ee7c6361355f4",
    "description": "Search",
    "docsUrl": null
  },
  ".gem-c-reorderable-list": {
    "name": "Reordable list",
    "key": "d3227a14e758432403bc2040f084c2666b56506b",
    "description": "Reordable list",
    "docsUrl": null
  },
  ".gem-c-image-card--large": {
    "name": "Size=Large",
    "key": "da44d7d78b1eed5c0ca704bbe3de00755b4977f6",
    "description": "Size=Large",
    "docsUrl": null
  },
  ".gem-c-intervention": {
    "name": "Intervention",
    "key": "e7e1bb24d186d7b88aea3d5c4e03f6b1be01b4fc",
    "description": "Intervention",
    "docsUrl": null
  },
  ".gem-c-global-banner": {
    "name": "Global banner",
    "key": "eb6260c8708f3a9be8a226576ade6aba2086b285",
    "description": "Global banner",
    "docsUrl": null
  },
  ".gem-c-emergency-banner--notable-death": {
    "name": "Campaign class=Notable death",
    "key": "f82e75064cef0d41556e26a44553eaf64e096b24",
    "description": "Campaign class=Notable death",
    "docsUrl": null
  },
  ".gem-c-contents-list": {
    "name": "Contents list",
    "key": "1d7de3147bb79f0bc7b4364ed5cc9105dfece568",
    "description": "Contents list",
    "docsUrl": null
  },
  ".gem-c-step-nav__step": {
    "name": "Step-by-step",
    "key": "95ae4427ee4746f83eb0c10d0d474ac9acfe79e7",
    "description": "Step-by-step",
    "docsUrl": null
  },
  ".gem-c-step-nav": {
    "name": "Step-by-step",
    "key": "a2714c436d9b0b8723534d9257e59aeb9affde54",
    "description": "Step-by-step",
    "docsUrl": null
  }
};

// ============================================================
// GOV.UK Page Builder (Cherry) — Figma Plugin
// No AI — fetches real page markup via Cloudflare Worker,
// extracts GOV.UK/gem-c classes, builds AutoLayout frame.
// ============================================================

var WORKER_URL = 'https://flat-night-ade1.nikin-nagewadia.workers.dev';

// Inlined from spacing-map.json
var SPACING_MAP = {
  scale: {
    "0":  { variableId: "VariableID:25:171", coreVariableId: "VariableID:25:171", source: "00 Core",       desktop: 0,  mobile: 0  },
    "1":  { variableId: "VariableID:25:173", coreVariableId: "VariableID:25:173", source: "00 Core",       desktop: 5,  mobile: 5  },
    "2":  { variableId: "VariableID:25:174", coreVariableId: "VariableID:25:174", source: "00 Core",       desktop: 10, mobile: 10 },
    "3":  { variableId: "VariableID:25:175", coreVariableId: "VariableID:25:175", source: "00 Core",       desktop: 15, mobile: 15 },
    "4":  { variableId: "VariableID:25:164", coreVariableId: "VariableID:25:176", source: "01 Responsive", desktop: 20, mobile: 15 },
    "5":  { variableId: "VariableID:25:165", coreVariableId: "VariableID:25:177", source: "01 Responsive", desktop: 25, mobile: 15 },
    "6":  { variableId: "VariableID:25:166", coreVariableId: "VariableID:25:178", source: "01 Responsive", desktop: 30, mobile: 20 },
    "7":  { variableId: "VariableID:25:167", coreVariableId: "VariableID:25:179", source: "01 Responsive", desktop: 40, mobile: 25 },
    "8":  { variableId: "VariableID:25:168", coreVariableId: "VariableID:25:180", source: "01 Responsive", desktop: 50, mobile: 30 },
    "9":  { variableId: "VariableID:25:169", coreVariableId: "VariableID:25:181", source: "01 Responsive", desktop: 60, mobile: 40 }
  },
  defaults: {
    componentGap:         "6",
    sidebarGap:           "6",
    contentPaddingTop:    "4",
    contentPaddingBottom: "9"
  }
};

figma.showUI(__html__, { width: 340, height: 220 });

// ── MESSAGE HANDLER ──────────────────────────────────────────
figma.ui.onmessage = async function (msg) {
  if (msg.type !== 'build') return;

  var url    = msg.url;
  var apiKey = msg.apiKey;

  try {
    if (Object.keys(COMPONENT_MAP).length === 0) throw new Error('Component map is empty. Run scanner.js first.');

    // Step 1: scrape HTML for accurate component list
    figma.ui.postMessage({ type: 'status', message: 'Fetching page markup…' });
    var rawComponents = await scrapeClasses(url);
    console.log('[cherry] raw components from page:', rawComponents);

    // Classes that are never visible on initial page load (CSS off-screen or JS-toggled)
    var EXCLUDE_CLASSES = new Set([
      '.govuk-skip-link',  // positioned off-screen, only visible on keyboard focus
      '.gem-c-search'      // search panel, hidden by default, shown on toggle
    ]);

    var matchedComponents = [];
    rawComponents.forEach(function (item) {
      var resolved = item.candidates.find(function (c) { return COMPONENT_MAP[c] && !EXCLUDE_CLASSES.has(c); });
      if (resolved) matchedComponents.push({ class: resolved, gridColumn: item.gridColumn, marginBottom: item.marginBottom });
    });
    console.log('[cherry] matched to component map:', matchedComponents);

    if (!matchedComponents.length) throw new Error('No recognised components found on this page. Check the URL and try again.');

    // Step 2: screenshot → Claude orders and filters the list
    figma.ui.postMessage({ type: 'status', message: 'Taking screenshot…' });
    var screenshot = await getScreenshot(url);

    figma.ui.postMessage({ type: 'status', message: 'Asking Claude to order components…' });
    var orderedComponents = await orderWithVision(matchedComponents, screenshot, apiKey);
    console.log('[cherry] Claude-ordered components:', orderedComponents);

    // Step 3: build the frame
    figma.ui.postMessage({ type: 'status', message: 'Building frame…' });
    await buildPage(orderedComponents, url);

    figma.ui.postMessage({ type: 'done' });
    figma.closePlugin();
  } catch (err) {
    figma.ui.postMessage({ type: 'error', message: err.message });
  }
};

// ── WORKER SCRAPE ─────────────────────────────────────────────
async function scrapeClasses(url) {
  var resp = await fetch(WORKER_URL + '?url=' + encodeURIComponent(url));
  if (!resp.ok) {
    var errText = await resp.text();
    throw new Error('Worker error ' + resp.status + ': ' + errText.substring(0, 200));
  }
  var data = await resp.json();
  if (data.error) throw new Error('Worker error: ' + data.error);
  return Array.isArray(data.components) ? data.components : [];
}

// ── SCREENSHOT + VISION ───────────────────────────────────────
function detectMediaType(bytes) {
  if (bytes[0] === 0xFF && bytes[1] === 0xD8) return 'image/jpeg';
  if (bytes[0] === 0x89 && bytes[1] === 0x50 && bytes[2] === 0x4E && bytes[3] === 0x47) return 'image/png';
  if (bytes[0] === 0x47 && bytes[1] === 0x49 && bytes[2] === 0x46) return 'image/gif';
  return 'image/png';
}

function uint8ToBase64(bytes) {
  var chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
  var base64 = '';
  var len = bytes.length;
  for (var i = 0; i < len - 2; i += 3) {
    base64 += chars[bytes[i] >> 2];
    base64 += chars[((bytes[i] & 3) << 4) | (bytes[i + 1] >> 4)];
    base64 += chars[((bytes[i + 1] & 15) << 2) | (bytes[i + 2] >> 6)];
    base64 += chars[bytes[i + 2] & 63];
  }
  var rem = len % 3;
  if (rem === 1) {
    base64 += chars[bytes[len - 1] >> 2];
    base64 += chars[(bytes[len - 1] & 3) << 4];
    base64 += '==';
  } else if (rem === 2) {
    base64 += chars[bytes[len - 2] >> 2];
    base64 += chars[((bytes[len - 2] & 3) << 4) | (bytes[len - 1] >> 4)];
    base64 += chars[(bytes[len - 1] & 15) << 2];
    base64 += '=';
  }
  return base64;
}

async function getScreenshot(url) {
  var thumUrl = 'https://image.thum.io/get/width/1440/noanimate/fullpage/' + url;
  var resp = await fetch(thumUrl);
  if (!resp.ok) throw new Error('Screenshot failed: HTTP ' + resp.status);
  var buffer = await resp.arrayBuffer();
  var bytes = new Uint8Array(buffer);
  return { base64: uint8ToBase64(bytes), mediaType: detectMediaType(bytes) };
}

async function orderWithVision(matchedComponents, screenshot, apiKey) {
  var classList = matchedComponents.map(function (item) { return item.class; });

  var prompt = 'The HTML markup of this GOV.UK page contains these components listed in their DOM order (top to bottom):\n' +
    classList.join('\n') +
    '\n\nLook at the screenshot and remove any components from the list that are clearly not visible on the page (e.g. hidden panels, off-screen elements). Keep all visible components in their original DOM order — do not reorder them. Return ONLY a valid JSON array of CSS class name strings — no markdown fences, no explanation. Example: [".govuk-header",".govuk-footer"]';

  var body = JSON.stringify({
    model: 'claude-opus-4-6',
    max_tokens: 1024,
    messages: [{
      role: 'user',
      content: [
        {
          type: 'image',
          source: { type: 'base64', media_type: screenshot.mediaType, data: screenshot.base64 }
        },
        { type: 'text', text: prompt }
      ]
    }]
  });

  var resp = await fetch(WORKER_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'x-api-key': apiKey, 'anthropic-version': '2023-06-01' },
    body: body
  });

  if (!resp.ok) {
    var errText = await resp.text();
    throw new Error('Anthropic API error ' + resp.status + ': ' + errText.substring(0, 300));
  }

  var data = await resp.json();
  if (data.error) throw new Error('Anthropic API error: ' + JSON.stringify(data.error));

  var text = (data.content && data.content[0] && data.content[0].text) || '';
  text = text.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '').trim();

  var orderedClasses;
  try {
    orderedClasses = JSON.parse(text);
  } catch (e) {
    console.warn('[vision] could not parse response:', text.substring(0, 300));
    return matchedComponents; // fall back to HTML order
  }

  if (!Array.isArray(orderedClasses) || orderedClasses.length === 0) return matchedComponents;

  // Remap to original items to preserve gridColumn/marginBottom context
  var classToItem = {};
  matchedComponents.forEach(function (item) { classToItem[item.class] = item; });

  var result = [];
  orderedClasses.forEach(function (cls) {
    if (classToItem[cls]) result.push(classToItem[cls]);
  });

  return result.length > 0 ? result : matchedComponents;
}

// ── COMPONENT CLASSIFICATION ──────────────────────────────────
var HEADER_SET  = new Set(['.gem-c-layout-super-navigation-header', '.gem-c-layout-header', '.gem-c-cross-service-header', '.govuk-header']);
var PHASE_SET   = new Set(['.govuk-phase-banner']);
var SNAV_SET    = new Set(['.govuk-service-navigation']);
var CRUMB_SET   = new Set(['.govuk-breadcrumbs']);
var SIDEBAR_COLUMNS = new Set([
  '.govuk-grid-column-one-third',
  '.govuk-grid-column-one-third-from-desktop',
  '.govuk-grid-column-one-quarter'
]);

function classifyComponents(components) {
  var out = {
    header: null,
    phaseBanner: null,
    serviceNav: null,
    breadcrumbs: null,
    mainContent: [],
    sidebar: [],
    footer: null
  };

  components.forEach(function (item) {
    var cssClass   = item.class;
    var inSidebar  = item.gridColumn && SIDEBAR_COLUMNS.has(item.gridColumn);

    if (HEADER_SET.has(cssClass) && !out.header) {
      out.header = { cssClass: cssClass };
    } else if (PHASE_SET.has(cssClass)) {
      out.phaseBanner = { cssClass: cssClass };
    } else if (SNAV_SET.has(cssClass)) {
      out.serviceNav = { cssClass: cssClass };
    } else if (CRUMB_SET.has(cssClass)) {
      out.breadcrumbs = { cssClass: cssClass };
    } else if (cssClass === '.govuk-footer' && !out.footer) {
      out.footer = { cssClass: cssClass };
    } else if (inSidebar) {
      out.sidebar.push({ cssClass: cssClass, marginBottom: item.marginBottom });
    } else {
      out.mainContent.push({ cssClass: cssClass, marginBottom: item.marginBottom });
    }
  });

  return out;
}

// ── FONTS ────────────────────────────────────────────────────
async function loadFonts() {
  try {
    await figma.loadFontAsync({ family: 'GDS Transport Website', style: 'Regular' });
    await figma.loadFontAsync({ family: 'GDS Transport Website', style: 'Bold' });
  } catch (_) {
    await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
    await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });
  }
}

// ── COMPONENT IMPORT ─────────────────────────────────────────
async function importComp(cssClass) {
  var entry = COMPONENT_MAP[cssClass];
  if (!entry) return null;
  for (var attempt = 0; attempt < 3; attempt++) {
    try {
      return await figma.importComponentByKeyAsync(entry.key);
    } catch (e) {
      if (attempt < 2) await new Promise(function (r) { setTimeout(r, 500 * (attempt + 1)); });
      else { console.warn('[skip] ' + cssClass + ': ' + e.message); return null; }
    }
  }
}

async function resolveAll(pageData) {
  var allClasses = [];
  var regions = ['header', 'phaseBanner', 'serviceNav', 'breadcrumbs', 'footer'];
  regions.forEach(function (r) {
    if (pageData[r]) allClasses.push(pageData[r].cssClass);
  });
  pageData.mainContent.forEach(function (i) { allClasses.push(i.cssClass); });
  pageData.sidebar.forEach(function (i) { allClasses.push(i.cssClass); });

  var resolved = {};
  var BATCH = 20;
  for (var i = 0; i < allClasses.length; i += BATCH) {
    var batch = allClasses.slice(i, i + BATCH);
    await Promise.all(batch.map(function (cssClass) {
      return importComp(cssClass).then(function (comp) { resolved[cssClass] = comp; });
    }));
  }

  var imported = Object.keys(resolved).filter(function (k) { return !!resolved[k]; }).length;
  console.log('[build] imported ' + imported + ' / ' + allClasses.length + ' components');
  return resolved;
}

// ── SPACING VARIABLES ─────────────────────────────────────────
async function bindSpacing(node, property, scaleKey) {
  var entry = SPACING_MAP.scale[scaleKey];
  if (!entry) return;
  try {
    var variable = await figma.variables.getVariableByIdAsync(entry.variableId);
    if (variable) { node.setBoundVariable(property, variable); return; }
  } catch (_) {}
  try { node[property] = entry.desktop; } catch (_) {}
}

// ── LAYOUT HELPERS ────────────────────────────────────────────
function makePlaceholder(cssClass, width) {
  var f = figma.createFrame();
  f.name = 'PLACEHOLDER: ' + cssClass;
  f.resize(Math.max(width, 100), 60);
  f.fills = [{ type: 'SOLID', color: { r: 1, g: 0.95, b: 0.8 } }];
  return f;
}

function placeComponent(cssClass, resolved, width) {
  var comp = resolved[cssClass];
  if (!comp) return makePlaceholder(cssClass, width);
  var instance = comp.createInstance();
  instance.name = cssClass;
  return instance;
}

async function populateColumn(col, items, resolved, width) {
  if (!items || !items.length) return;
  for (var i = 0; i < items.length; i++) {
    var item = items[i];
    var node = placeComponent(item.cssClass, resolved, width);
    col.appendChild(node);
    try { node.layoutSizingHorizontal = 'FILL'; } catch (_) {}
    if (item.marginBottom) {
      var entry = SPACING_MAP.scale[item.marginBottom.scale];
      if (entry) {
        var varId = item.marginBottom.static ? entry.coreVariableId : entry.variableId;
        try {
          var variable = await figma.variables.getVariableByIdAsync(varId);
          if (variable) { node.setBoundVariable('marginBottom', variable); }
        } catch (_) {}
      }
    }
  }
}

function makeAutoFrame(name, direction, width) {
  var f = figma.createFrame();
  f.name = name;
  f.layoutMode = direction;
  f.primaryAxisSizingMode = 'AUTO';
  f.counterAxisSizingMode = width ? 'FIXED' : 'AUTO';
  if (width) f.resize(width, 100);
  f.fills = [];
  f.clipsContent = false;
  return f;
}

// ── FRAME BUILDER ─────────────────────────────────────────────
async function buildFrame(pageData, resolved, frameWidth, frameName, layout) {
  var frame = makeAutoFrame(frameName, 'VERTICAL', frameWidth);
  frame.fills = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];
  frame.itemSpacing = 0;

  function addFullWidth(cssClass) {
    if (!cssClass) return;
    var node = placeComponent(cssClass, resolved, frameWidth);
    frame.appendChild(node);
    try { node.layoutSizingHorizontal = 'FILL'; } catch (_) {}
    try { node.resize(frameWidth, node.height); } catch (_) {}
  }

  if (pageData.header)      addFullWidth(pageData.header.cssClass);
  if (pageData.phaseBanner) addFullWidth(pageData.phaseBanner.cssClass);
  if (pageData.serviceNav)  addFullWidth(pageData.serviceNav.cssClass);

  var contentWrapper = makeAutoFrame('Content', 'VERTICAL', null);
  contentWrapper.paddingLeft  = layout.margin;
  contentWrapper.paddingRight = layout.margin;
  frame.appendChild(contentWrapper);
  try { contentWrapper.layoutSizingHorizontal = 'FILL'; } catch (_) {}
  await bindSpacing(contentWrapper, 'paddingTop',    SPACING_MAP.defaults.contentPaddingTop);
  await bindSpacing(contentWrapper, 'paddingBottom', SPACING_MAP.defaults.contentPaddingBottom);
  await bindSpacing(contentWrapper, 'itemSpacing',   SPACING_MAP.defaults.componentGap);

  if (pageData.breadcrumbs) {
    var bc = placeComponent(pageData.breadcrumbs.cssClass, resolved, layout.contentWidth);
    contentWrapper.appendChild(bc);
    try { bc.layoutSizingHorizontal = 'FILL'; } catch (_) {}
  }

  var bodyRow = makeAutoFrame('Body', 'HORIZONTAL', null);
  bodyRow.counterAxisAlignItems = 'MIN';
  contentWrapper.appendChild(bodyRow);
  try { bodyRow.layoutSizingHorizontal = 'FILL'; } catch (_) {}
  await bindSpacing(bodyRow, 'itemSpacing', SPACING_MAP.defaults.componentGap);

  var mainCol = makeAutoFrame('Main content', 'VERTICAL', layout.contentWidth);
  await populateColumn(mainCol, pageData.mainContent, resolved, layout.contentWidth);
  bodyRow.appendChild(mainCol);
  await bindSpacing(mainCol, 'itemSpacing', SPACING_MAP.defaults.componentGap);

  if (pageData.sidebar.length > 0) {
    var sideCol = makeAutoFrame('Sidebar', 'VERTICAL', layout.sidebarWidth);
    await populateColumn(sideCol, pageData.sidebar, resolved, layout.sidebarWidth);
    bodyRow.appendChild(sideCol);
    await bindSpacing(sideCol, 'itemSpacing', SPACING_MAP.defaults.sidebarGap);
  }

  if (pageData.footer) addFullWidth(pageData.footer.cssClass);

  return frame;
}

// ── MAIN PAGE BUILDER ─────────────────────────────────────────
async function buildPage(detectedClasses, sourceUrl) {
  await loadFonts();

  var pageData = classifyComponents(detectedClasses);
  var resolved = await resolveAll(pageData);

  var pageName = sourceUrl.replace(/^https?:\/\/[^/]+/, '').replace(/\/$/, '') || 'GOV.UK Page';

  var existing = figma.root.children.find(function (p) { return p.name === pageName; });
  if (existing) existing.remove();
  var page = figma.createPage();
  page.name = pageName;
  await figma.setCurrentPageAsync(page);

  figma.notify('Building page…', { timeout: 60000 });
  var df = await buildFrame(pageData, resolved, 1440, 'Desktop — 1440px', {
    margin: 240, contentWidth: 640, sidebarWidth: 290, gap: 30
  });
  df.x = 0; df.y = 0;
  page.appendChild(df);

  figma.viewport.scrollAndZoomIntoView([df]);
}
